-- Migration bổ sung để khớp Frontend types.ts
-- Chạy trên DB admission_db (MariaDB/MySQL) trước khi start Backend

ALTER TABLE candidate
  ADD COLUMN IF NOT EXISTS dob DATE NULL,
  ADD COLUMN IF NOT EXISTS gender VARCHAR(10) NULL,
  ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL;

ALTER TABLE admission_batch
  ADD COLUMN IF NOT EXISTS batch_name VARCHAR(200) NULL;

ALTER TABLE admission_major
  ADD COLUMN IF NOT EXISTS major_name VARCHAR(200) NULL;

ALTER TABLE lecturer
  ADD COLUMN IF NOT EXISTS full_name VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS faculty_name VARCHAR(200) NULL;

ALTER TABLE application_document
  ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS verify_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE otp_verification
  ADD COLUMN IF NOT EXISTS otp_code_hash VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE supervisor_request
  ADD COLUMN IF NOT EXISTS created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS complaint (
  complaint_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  candidate_id BIGINT NOT NULL,
  application_code VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
