org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Dùng cố định JDK 17 cho Gradle, không phụ thuộc JAVA_HOME hệ thống
org.gradle.java.home=C:/Users/ADMIN/.jdks/temurin-17.0.20.1
